### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by bobdm4** [bobdm4/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by borys-demchenko** [comment]
2014
Relocate to Irpin and joining up to Univesity of state tax service of Ukraine 
2019
Finished the full stack course GoIT
2020
Got my first job at IT in v7kupon web studio
2021
Front end developer in Aivix
