### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by bobdm4** [bobdm4/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by borys-demchenko** [comment]
LANGUAGES
🇺🇦 УКРАЇНСЬКА 🇷🇺 РУССКИЙ 🇺🇸 ENGLISH

SKILLS
HTML CSS JS JQUERY REACT REDUX GULP NODEJS NPM BOOTSTRAP SEMANTIC UI LESS SASS CSS-IN-JS PRETTIER ESLINT AWS TRAVIS MICROSOFT OFFICE PHOTOSHOP FIGMA WINDOWS
